version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always  
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always    
    ports:
      - "5054:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./audio-data:/app/audio

volumes:
  audio-data:  