version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always  
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always    
    ports:
      - "5054:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./audio-data:/app/audio

  # ytdl-mongo-db:
  #       # If you are using a Raspberry Pi, use mongo:4.4.18
  #       image: mongo:4
  #       logging:
  #           driver: "json-file"        
  #       container_name: mongo-db
  #       restart: always
  #       ports:
  #           - "27017:27017"
  #       volumes:
  #           - ./db/:/data/db
            
volumes:
  audio-data:  
networks:
  default:
    name: ytdl_default
    external: true        